namespace tp_navBtns_CRUD {
    partial class mainController {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent() {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(mainController));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.exitIcon = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.removeStgBtn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.modifyStgBtn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.addStgBtn = new Bunifu.Framework.UI.BunifuThinButton2();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.resetBtn = new Bunifu.UI.WinForms.BunifuImageButton();
            this.searchByTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.clearIcon = new Bunifu.UI.WinForms.BunifuImageButton();
            this.saveChangesIcon = new Bunifu.UI.WinForms.BunifuImageButton();
            this.itemNumberLbl = new Bunifu.UI.WinForms.BunifuLabel();
            this.toLastBtn = new Guna.UI2.WinForms.Guna2CircleButton();
            this.previousBtn = new Guna.UI2.WinForms.Guna2CircleButton();
            this.nextBtn = new Guna.UI2.WinForms.Guna2CircleButton();
            this.toZeroBtn = new Guna.UI2.WinForms.Guna2CircleButton();
            this.ageTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.cinTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.addressTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.prenomTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nomTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.idTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGradientPanel1.SuspendLayout();
            this.bunifuPanel3.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 5;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.exitIcon);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPanel3);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPanel1);
            this.bunifuGradientPanel1.Controls.Add(this.dgv);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.DeepPink;
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.DodgerBlue;
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(198)))), ((int)(((byte)(60)))), ((int)(((byte)(212)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(958, 450);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // exitIcon
            // 
            this.exitIcon.ActiveImage = null;
            this.exitIcon.AllowAnimations = true;
            this.exitIcon.AllowBuffering = false;
            this.exitIcon.AllowToggling = false;
            this.exitIcon.AllowZooming = true;
            this.exitIcon.AllowZoomingOnFocus = false;
            this.exitIcon.BackColor = System.Drawing.Color.Transparent;
            this.exitIcon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exitIcon.ErrorImage = ((System.Drawing.Image)(resources.GetObject("exitIcon.ErrorImage")));
            this.exitIcon.FadeWhenInactive = false;
            this.exitIcon.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.exitIcon.Image = global::tp_navBtns_CRUD.Properties.Resources.clear;
            this.exitIcon.ImageActive = null;
            this.exitIcon.ImageLocation = null;
            this.exitIcon.ImageMargin = 20;
            this.exitIcon.ImageSize = new System.Drawing.Size(30, 30);
            this.exitIcon.ImageZoomSize = new System.Drawing.Size(50, 50);
            this.exitIcon.InitialImage = ((System.Drawing.Image)(resources.GetObject("exitIcon.InitialImage")));
            this.exitIcon.Location = new System.Drawing.Point(908, -1);
            this.exitIcon.Name = "exitIcon";
            this.exitIcon.Rotation = 0;
            this.exitIcon.ShowActiveImage = true;
            this.exitIcon.ShowCursorChanges = true;
            this.exitIcon.ShowImageBorders = true;
            this.exitIcon.ShowSizeMarkers = false;
            this.exitIcon.Size = new System.Drawing.Size(50, 50);
            this.exitIcon.TabIndex = 14;
            this.exitIcon.ToolTipText = "";
            this.exitIcon.WaitOnLoad = false;
            this.exitIcon.Zoom = 20;
            this.exitIcon.ZoomSpeed = 10;
            this.exitIcon.Click += new System.EventHandler(this.exitIcon_Click);
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 3;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Controls.Add(this.removeStgBtn);
            this.bunifuPanel3.Controls.Add(this.modifyStgBtn);
            this.bunifuPanel3.Controls.Add(this.addStgBtn);
            this.bunifuPanel3.Location = new System.Drawing.Point(42, 376);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(617, 50);
            this.bunifuPanel3.TabIndex = 3;
            // 
            // removeStgBtn
            // 
            this.removeStgBtn.ActiveBorderThickness = 1;
            this.removeStgBtn.ActiveCornerRadius = 20;
            this.removeStgBtn.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.removeStgBtn.ActiveForecolor = System.Drawing.Color.White;
            this.removeStgBtn.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.removeStgBtn.BackColor = System.Drawing.Color.Transparent;
            this.removeStgBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("removeStgBtn.BackgroundImage")));
            this.removeStgBtn.ButtonText = "Delete";
            this.removeStgBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.removeStgBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.removeStgBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.removeStgBtn.IdleBorderThickness = 1;
            this.removeStgBtn.IdleCornerRadius = 20;
            this.removeStgBtn.IdleFillColor = System.Drawing.Color.White;
            this.removeStgBtn.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.removeStgBtn.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.removeStgBtn.Location = new System.Drawing.Point(434, 5);
            this.removeStgBtn.Margin = new System.Windows.Forms.Padding(5);
            this.removeStgBtn.Name = "removeStgBtn";
            this.removeStgBtn.Size = new System.Drawing.Size(181, 41);
            this.removeStgBtn.TabIndex = 5;
            this.removeStgBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.removeStgBtn.Click += new System.EventHandler(this.CRUD_Btn_Click);
            // 
            // modifyStgBtn
            // 
            this.modifyStgBtn.ActiveBorderThickness = 1;
            this.modifyStgBtn.ActiveCornerRadius = 20;
            this.modifyStgBtn.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.modifyStgBtn.ActiveForecolor = System.Drawing.Color.White;
            this.modifyStgBtn.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.modifyStgBtn.BackColor = System.Drawing.Color.Transparent;
            this.modifyStgBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("modifyStgBtn.BackgroundImage")));
            this.modifyStgBtn.ButtonText = "Update";
            this.modifyStgBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.modifyStgBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.modifyStgBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.modifyStgBtn.IdleBorderThickness = 1;
            this.modifyStgBtn.IdleCornerRadius = 20;
            this.modifyStgBtn.IdleFillColor = System.Drawing.Color.White;
            this.modifyStgBtn.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.modifyStgBtn.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.modifyStgBtn.Location = new System.Drawing.Point(217, 5);
            this.modifyStgBtn.Margin = new System.Windows.Forms.Padding(5);
            this.modifyStgBtn.Name = "modifyStgBtn";
            this.modifyStgBtn.Size = new System.Drawing.Size(181, 41);
            this.modifyStgBtn.TabIndex = 6;
            this.modifyStgBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.modifyStgBtn.Click += new System.EventHandler(this.CRUD_Btn_Click);
            // 
            // addStgBtn
            // 
            this.addStgBtn.ActiveBorderThickness = 1;
            this.addStgBtn.ActiveCornerRadius = 20;
            this.addStgBtn.ActiveFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.addStgBtn.ActiveForecolor = System.Drawing.Color.White;
            this.addStgBtn.ActiveLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.addStgBtn.BackColor = System.Drawing.Color.Transparent;
            this.addStgBtn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addStgBtn.BackgroundImage")));
            this.addStgBtn.ButtonText = "Insert";
            this.addStgBtn.Cursor = System.Windows.Forms.Cursors.Hand;
            this.addStgBtn.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addStgBtn.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.addStgBtn.IdleBorderThickness = 1;
            this.addStgBtn.IdleCornerRadius = 20;
            this.addStgBtn.IdleFillColor = System.Drawing.Color.White;
            this.addStgBtn.IdleForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.addStgBtn.IdleLineColor = System.Drawing.Color.FromArgb(((int)(((byte)(236)))), ((int)(((byte)(92)))), ((int)(((byte)(188)))));
            this.addStgBtn.Location = new System.Drawing.Point(1, 5);
            this.addStgBtn.Margin = new System.Windows.Forms.Padding(5);
            this.addStgBtn.Name = "addStgBtn";
            this.addStgBtn.Size = new System.Drawing.Size(181, 41);
            this.addStgBtn.TabIndex = 7;
            this.addStgBtn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addStgBtn.Click += new System.EventHandler(this.CRUD_Btn_Click);
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.resetBtn);
            this.bunifuPanel2.Controls.Add(this.searchByTB);
            this.bunifuPanel2.Location = new System.Drawing.Point(42, 3);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(617, 50);
            this.bunifuPanel2.TabIndex = 3;
            // 
            // resetBtn
            // 
            this.resetBtn.ActiveImage = null;
            this.resetBtn.AllowAnimations = true;
            this.resetBtn.AllowBuffering = false;
            this.resetBtn.AllowToggling = false;
            this.resetBtn.AllowZooming = true;
            this.resetBtn.AllowZoomingOnFocus = false;
            this.resetBtn.BackColor = System.Drawing.Color.Transparent;
            this.resetBtn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.resetBtn.ErrorImage = ((System.Drawing.Image)(resources.GetObject("resetBtn.ErrorImage")));
            this.resetBtn.FadeWhenInactive = false;
            this.resetBtn.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.resetBtn.Image = global::tp_navBtns_CRUD.Properties.Resources.update;
            this.resetBtn.ImageActive = null;
            this.resetBtn.ImageLocation = null;
            this.resetBtn.ImageMargin = 20;
            this.resetBtn.ImageSize = new System.Drawing.Size(30, 30);
            this.resetBtn.ImageZoomSize = new System.Drawing.Size(50, 50);
            this.resetBtn.InitialImage = ((System.Drawing.Image)(resources.GetObject("resetBtn.InitialImage")));
            this.resetBtn.Location = new System.Drawing.Point(0, 0);
            this.resetBtn.Name = "resetBtn";
            this.resetBtn.Rotation = 0;
            this.resetBtn.ShowActiveImage = true;
            this.resetBtn.ShowCursorChanges = true;
            this.resetBtn.ShowImageBorders = true;
            this.resetBtn.ShowSizeMarkers = false;
            this.resetBtn.Size = new System.Drawing.Size(50, 50);
            this.resetBtn.TabIndex = 10;
            this.resetBtn.ToolTipText = "";
            this.resetBtn.WaitOnLoad = false;
            this.resetBtn.Zoom = 20;
            this.resetBtn.ZoomSpeed = 10;
            this.resetBtn.Click += new System.EventHandler(this.resetBtn_Click);
            // 
            // searchByTB
            // 
            this.searchByTB.AcceptsReturn = false;
            this.searchByTB.AcceptsTab = false;
            this.searchByTB.AnimationSpeed = 200;
            this.searchByTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchByTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchByTB.AutoSizeHeight = true;
            this.searchByTB.BackColor = System.Drawing.Color.Transparent;
            this.searchByTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchByTB.BackgroundImage")));
            this.searchByTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.searchByTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchByTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.searchByTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchByTB.BorderRadius = 1;
            this.searchByTB.BorderThickness = 1;
            this.searchByTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchByTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchByTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.searchByTB.DefaultText = "";
            this.searchByTB.FillColor = System.Drawing.Color.White;
            this.searchByTB.HideSelection = true;
            this.searchByTB.IconLeft = null;
            this.searchByTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchByTB.IconPadding = 10;
            this.searchByTB.IconRight = global::tp_navBtns_CRUD.Properties.Resources._728952_magnifier_zoom_explore_find_look_icon;
            this.searchByTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchByTB.Lines = new string[0];
            this.searchByTB.Location = new System.Drawing.Point(414, 8);
            this.searchByTB.MaxLength = 32767;
            this.searchByTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchByTB.Modified = false;
            this.searchByTB.Multiline = false;
            this.searchByTB.Name = "searchByTB";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchByTB.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchByTB.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchByTB.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchByTB.OnIdleState = stateProperties4;
            this.searchByTB.Padding = new System.Windows.Forms.Padding(3);
            this.searchByTB.PasswordChar = '\0';
            this.searchByTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchByTB.PlaceholderText = "Search by CIN ";
            this.searchByTB.ReadOnly = false;
            this.searchByTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchByTB.SelectedText = "";
            this.searchByTB.SelectionLength = 0;
            this.searchByTB.SelectionStart = 0;
            this.searchByTB.ShortcutsEnabled = true;
            this.searchByTB.Size = new System.Drawing.Size(200, 39);
            this.searchByTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchByTB.TabIndex = 8;
            this.searchByTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchByTB.TextMarginBottom = 0;
            this.searchByTB.TextMarginLeft = 3;
            this.searchByTB.TextMarginTop = 1;
            this.searchByTB.TextPlaceholder = "Search by CIN ";
            this.searchByTB.UseSystemPasswordChar = false;
            this.searchByTB.WordWrap = true;
            this.searchByTB.KeyDown += new System.Windows.Forms.KeyEventHandler(this.searchByTB_KeyDown);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.clearIcon);
            this.bunifuPanel1.Controls.Add(this.saveChangesIcon);
            this.bunifuPanel1.Controls.Add(this.itemNumberLbl);
            this.bunifuPanel1.Controls.Add(this.toLastBtn);
            this.bunifuPanel1.Controls.Add(this.previousBtn);
            this.bunifuPanel1.Controls.Add(this.nextBtn);
            this.bunifuPanel1.Controls.Add(this.toZeroBtn);
            this.bunifuPanel1.Controls.Add(this.ageTB);
            this.bunifuPanel1.Controls.Add(this.cinTB);
            this.bunifuPanel1.Controls.Add(this.addressTB);
            this.bunifuPanel1.Controls.Add(this.prenomTB);
            this.bunifuPanel1.Controls.Add(this.nomTB);
            this.bunifuPanel1.Controls.Add(this.idTB);
            this.bunifuPanel1.Location = new System.Drawing.Point(682, 11);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(241, 427);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // clearIcon
            // 
            this.clearIcon.ActiveImage = null;
            this.clearIcon.AllowAnimations = true;
            this.clearIcon.AllowBuffering = false;
            this.clearIcon.AllowToggling = false;
            this.clearIcon.AllowZooming = true;
            this.clearIcon.AllowZoomingOnFocus = false;
            this.clearIcon.BackColor = System.Drawing.Color.Transparent;
            this.clearIcon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.clearIcon.ErrorImage = ((System.Drawing.Image)(resources.GetObject("clearIcon.ErrorImage")));
            this.clearIcon.FadeWhenInactive = false;
            this.clearIcon.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.clearIcon.Image = global::tp_navBtns_CRUD.Properties.Resources.dust;
            this.clearIcon.ImageActive = null;
            this.clearIcon.ImageLocation = null;
            this.clearIcon.ImageMargin = 20;
            this.clearIcon.ImageSize = new System.Drawing.Size(30, 30);
            this.clearIcon.ImageZoomSize = new System.Drawing.Size(50, 50);
            this.clearIcon.InitialImage = ((System.Drawing.Image)(resources.GetObject("clearIcon.InitialImage")));
            this.clearIcon.Location = new System.Drawing.Point(171, 319);
            this.clearIcon.Name = "clearIcon";
            this.clearIcon.Rotation = 0;
            this.clearIcon.ShowActiveImage = true;
            this.clearIcon.ShowCursorChanges = true;
            this.clearIcon.ShowImageBorders = true;
            this.clearIcon.ShowSizeMarkers = false;
            this.clearIcon.Size = new System.Drawing.Size(50, 50);
            this.clearIcon.TabIndex = 14;
            this.clearIcon.ToolTipText = "";
            this.clearIcon.WaitOnLoad = false;
            this.clearIcon.Zoom = 20;
            this.clearIcon.ZoomSpeed = 10;
            this.clearIcon.Click += new System.EventHandler(this.clearIcon_Click_1);
            // 
            // saveChangesIcon
            // 
            this.saveChangesIcon.ActiveImage = null;
            this.saveChangesIcon.AllowAnimations = true;
            this.saveChangesIcon.AllowBuffering = false;
            this.saveChangesIcon.AllowToggling = false;
            this.saveChangesIcon.AllowZooming = true;
            this.saveChangesIcon.AllowZoomingOnFocus = false;
            this.saveChangesIcon.BackColor = System.Drawing.Color.Transparent;
            this.saveChangesIcon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveChangesIcon.ErrorImage = ((System.Drawing.Image)(resources.GetObject("saveChangesIcon.ErrorImage")));
            this.saveChangesIcon.FadeWhenInactive = false;
            this.saveChangesIcon.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.saveChangesIcon.Image = global::tp_navBtns_CRUD.Properties.Resources.accept;
            this.saveChangesIcon.ImageActive = null;
            this.saveChangesIcon.ImageLocation = null;
            this.saveChangesIcon.ImageMargin = 20;
            this.saveChangesIcon.ImageSize = new System.Drawing.Size(30, 30);
            this.saveChangesIcon.ImageZoomSize = new System.Drawing.Size(50, 50);
            this.saveChangesIcon.InitialImage = ((System.Drawing.Image)(resources.GetObject("saveChangesIcon.InitialImage")));
            this.saveChangesIcon.Location = new System.Drawing.Point(21, 319);
            this.saveChangesIcon.Name = "saveChangesIcon";
            this.saveChangesIcon.Rotation = 0;
            this.saveChangesIcon.ShowActiveImage = true;
            this.saveChangesIcon.ShowCursorChanges = true;
            this.saveChangesIcon.ShowImageBorders = true;
            this.saveChangesIcon.ShowSizeMarkers = false;
            this.saveChangesIcon.Size = new System.Drawing.Size(50, 50);
            this.saveChangesIcon.TabIndex = 14;
            this.saveChangesIcon.ToolTipText = "";
            this.saveChangesIcon.WaitOnLoad = false;
            this.saveChangesIcon.Zoom = 20;
            this.saveChangesIcon.ZoomSpeed = 10;
            this.saveChangesIcon.Click += new System.EventHandler(this.saveChangesIcon_Click);
            // 
            // itemNumberLbl
            // 
            this.itemNumberLbl.AllowParentOverrides = false;
            this.itemNumberLbl.AutoEllipsis = false;
            this.itemNumberLbl.Cursor = System.Windows.Forms.Cursors.Default;
            this.itemNumberLbl.CursorType = System.Windows.Forms.Cursors.Default;
            this.itemNumberLbl.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.itemNumberLbl.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(94)))), ((int)(((byte)(148)))), ((int)(((byte)(255)))));
            this.itemNumberLbl.Location = new System.Drawing.Point(70, 17);
            this.itemNumberLbl.Name = "itemNumberLbl";
            this.itemNumberLbl.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.itemNumberLbl.Size = new System.Drawing.Size(0, 0);
            this.itemNumberLbl.TabIndex = 13;
            this.itemNumberLbl.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.itemNumberLbl.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // toLastBtn
            // 
            this.toLastBtn.CheckedState.Parent = this.toLastBtn;
            this.toLastBtn.CustomImages.Parent = this.toLastBtn;
            this.toLastBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.toLastBtn.ForeColor = System.Drawing.Color.White;
            this.toLastBtn.HoverState.Parent = this.toLastBtn;
            this.toLastBtn.Location = new System.Drawing.Point(183, 368);
            this.toLastBtn.Name = "toLastBtn";
            this.toLastBtn.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.toLastBtn.ShadowDecoration.Parent = this.toLastBtn;
            this.toLastBtn.Size = new System.Drawing.Size(48, 47);
            this.toLastBtn.TabIndex = 9;
            this.toLastBtn.Text = ">>";
            this.toLastBtn.Click += new System.EventHandler(this.navBtn_Click);
            // 
            // previousBtn
            // 
            this.previousBtn.CheckedState.Parent = this.previousBtn;
            this.previousBtn.CustomImages.Parent = this.previousBtn;
            this.previousBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.previousBtn.ForeColor = System.Drawing.Color.White;
            this.previousBtn.HoverState.Parent = this.previousBtn;
            this.previousBtn.Location = new System.Drawing.Point(75, 368);
            this.previousBtn.Name = "previousBtn";
            this.previousBtn.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.previousBtn.ShadowDecoration.Parent = this.previousBtn;
            this.previousBtn.Size = new System.Drawing.Size(48, 47);
            this.previousBtn.TabIndex = 10;
            this.previousBtn.Text = "<";
            this.previousBtn.Click += new System.EventHandler(this.navBtn_Click);
            // 
            // nextBtn
            // 
            this.nextBtn.CheckedState.Parent = this.nextBtn;
            this.nextBtn.CustomImages.Parent = this.nextBtn;
            this.nextBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.nextBtn.ForeColor = System.Drawing.Color.White;
            this.nextBtn.HoverState.Parent = this.nextBtn;
            this.nextBtn.Location = new System.Drawing.Point(129, 368);
            this.nextBtn.Name = "nextBtn";
            this.nextBtn.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.nextBtn.ShadowDecoration.Parent = this.nextBtn;
            this.nextBtn.Size = new System.Drawing.Size(48, 47);
            this.nextBtn.TabIndex = 11;
            this.nextBtn.Text = ">";
            this.nextBtn.Click += new System.EventHandler(this.navBtn_Click);
            // 
            // toZeroBtn
            // 
            this.toZeroBtn.CheckedState.Parent = this.toZeroBtn;
            this.toZeroBtn.CustomImages.Parent = this.toZeroBtn;
            this.toZeroBtn.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.toZeroBtn.ForeColor = System.Drawing.Color.White;
            this.toZeroBtn.HoverState.Parent = this.toZeroBtn;
            this.toZeroBtn.Location = new System.Drawing.Point(21, 368);
            this.toZeroBtn.Name = "toZeroBtn";
            this.toZeroBtn.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            this.toZeroBtn.ShadowDecoration.Parent = this.toZeroBtn;
            this.toZeroBtn.Size = new System.Drawing.Size(48, 47);
            this.toZeroBtn.TabIndex = 12;
            this.toZeroBtn.Text = "<<";
            this.toZeroBtn.Click += new System.EventHandler(this.navBtn_Click);
            // 
            // ageTB
            // 
            this.ageTB.AcceptsReturn = false;
            this.ageTB.AcceptsTab = false;
            this.ageTB.AnimationSpeed = 200;
            this.ageTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ageTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ageTB.AutoSizeHeight = true;
            this.ageTB.BackColor = System.Drawing.Color.Transparent;
            this.ageTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ageTB.BackgroundImage")));
            this.ageTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.ageTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ageTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ageTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.ageTB.BorderRadius = 1;
            this.ageTB.BorderThickness = 1;
            this.ageTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ageTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ageTB.DefaultText = "";
            this.ageTB.FillColor = System.Drawing.Color.White;
            this.ageTB.HideSelection = true;
            this.ageTB.IconLeft = null;
            this.ageTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTB.IconPadding = 10;
            this.ageTB.IconRight = null;
            this.ageTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ageTB.Lines = new string[0];
            this.ageTB.Location = new System.Drawing.Point(21, 274);
            this.ageTB.MaxLength = 32767;
            this.ageTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.ageTB.Modified = false;
            this.ageTB.Multiline = false;
            this.ageTB.Name = "ageTB";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTB.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ageTB.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTB.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ageTB.OnIdleState = stateProperties8;
            this.ageTB.Padding = new System.Windows.Forms.Padding(3);
            this.ageTB.PasswordChar = '\0';
            this.ageTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.ageTB.PlaceholderText = "age";
            this.ageTB.ReadOnly = false;
            this.ageTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ageTB.SelectedText = "";
            this.ageTB.SelectionLength = 0;
            this.ageTB.SelectionStart = 0;
            this.ageTB.ShortcutsEnabled = true;
            this.ageTB.Size = new System.Drawing.Size(200, 39);
            this.ageTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ageTB.TabIndex = 3;
            this.ageTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ageTB.TextMarginBottom = 0;
            this.ageTB.TextMarginLeft = 3;
            this.ageTB.TextMarginTop = 1;
            this.ageTB.TextPlaceholder = "age";
            this.ageTB.UseSystemPasswordChar = false;
            this.ageTB.WordWrap = true;
            // 
            // cinTB
            // 
            this.cinTB.AcceptsReturn = false;
            this.cinTB.AcceptsTab = false;
            this.cinTB.AnimationSpeed = 200;
            this.cinTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cinTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cinTB.AutoSizeHeight = true;
            this.cinTB.BackColor = System.Drawing.Color.Transparent;
            this.cinTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cinTB.BackgroundImage")));
            this.cinTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cinTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cinTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cinTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.cinTB.BorderRadius = 1;
            this.cinTB.BorderThickness = 1;
            this.cinTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cinTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cinTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.cinTB.DefaultText = "";
            this.cinTB.FillColor = System.Drawing.Color.White;
            this.cinTB.HideSelection = true;
            this.cinTB.IconLeft = null;
            this.cinTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cinTB.IconPadding = 10;
            this.cinTB.IconRight = null;
            this.cinTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cinTB.Lines = new string[0];
            this.cinTB.Location = new System.Drawing.Point(21, 229);
            this.cinTB.MaxLength = 32767;
            this.cinTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.cinTB.Modified = false;
            this.cinTB.Multiline = false;
            this.cinTB.Name = "cinTB";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cinTB.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cinTB.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cinTB.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cinTB.OnIdleState = stateProperties12;
            this.cinTB.Padding = new System.Windows.Forms.Padding(3);
            this.cinTB.PasswordChar = '\0';
            this.cinTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cinTB.PlaceholderText = "CIN";
            this.cinTB.ReadOnly = false;
            this.cinTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cinTB.SelectedText = "";
            this.cinTB.SelectionLength = 0;
            this.cinTB.SelectionStart = 0;
            this.cinTB.ShortcutsEnabled = true;
            this.cinTB.Size = new System.Drawing.Size(200, 39);
            this.cinTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cinTB.TabIndex = 4;
            this.cinTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cinTB.TextMarginBottom = 0;
            this.cinTB.TextMarginLeft = 3;
            this.cinTB.TextMarginTop = 1;
            this.cinTB.TextPlaceholder = "CIN";
            this.cinTB.UseSystemPasswordChar = false;
            this.cinTB.WordWrap = true;
            // 
            // addressTB
            // 
            this.addressTB.AcceptsReturn = false;
            this.addressTB.AcceptsTab = false;
            this.addressTB.AnimationSpeed = 200;
            this.addressTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressTB.AutoSizeHeight = true;
            this.addressTB.BackColor = System.Drawing.Color.Transparent;
            this.addressTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressTB.BackgroundImage")));
            this.addressTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.addressTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addressTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressTB.BorderRadius = 1;
            this.addressTB.BorderThickness = 1;
            this.addressTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressTB.DefaultText = "";
            this.addressTB.FillColor = System.Drawing.Color.White;
            this.addressTB.HideSelection = true;
            this.addressTB.IconLeft = null;
            this.addressTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.IconPadding = 10;
            this.addressTB.IconRight = null;
            this.addressTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.Lines = new string[0];
            this.addressTB.Location = new System.Drawing.Point(21, 184);
            this.addressTB.MaxLength = 32767;
            this.addressTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressTB.Modified = false;
            this.addressTB.Multiline = false;
            this.addressTB.Name = "addressTB";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressTB.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnIdleState = stateProperties16;
            this.addressTB.Padding = new System.Windows.Forms.Padding(3);
            this.addressTB.PasswordChar = '\0';
            this.addressTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressTB.PlaceholderText = "address";
            this.addressTB.ReadOnly = false;
            this.addressTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressTB.SelectedText = "";
            this.addressTB.SelectionLength = 0;
            this.addressTB.SelectionStart = 0;
            this.addressTB.ShortcutsEnabled = true;
            this.addressTB.Size = new System.Drawing.Size(200, 39);
            this.addressTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressTB.TabIndex = 5;
            this.addressTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressTB.TextMarginBottom = 0;
            this.addressTB.TextMarginLeft = 3;
            this.addressTB.TextMarginTop = 1;
            this.addressTB.TextPlaceholder = "address";
            this.addressTB.UseSystemPasswordChar = false;
            this.addressTB.WordWrap = true;
            // 
            // prenomTB
            // 
            this.prenomTB.AcceptsReturn = false;
            this.prenomTB.AcceptsTab = false;
            this.prenomTB.AnimationSpeed = 200;
            this.prenomTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.prenomTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.prenomTB.AutoSizeHeight = true;
            this.prenomTB.BackColor = System.Drawing.Color.Transparent;
            this.prenomTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("prenomTB.BackgroundImage")));
            this.prenomTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.prenomTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.prenomTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.prenomTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.prenomTB.BorderRadius = 1;
            this.prenomTB.BorderThickness = 1;
            this.prenomTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.prenomTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.prenomTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.prenomTB.DefaultText = "";
            this.prenomTB.FillColor = System.Drawing.Color.White;
            this.prenomTB.HideSelection = true;
            this.prenomTB.IconLeft = null;
            this.prenomTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.prenomTB.IconPadding = 10;
            this.prenomTB.IconRight = null;
            this.prenomTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.prenomTB.Lines = new string[0];
            this.prenomTB.Location = new System.Drawing.Point(21, 139);
            this.prenomTB.MaxLength = 32767;
            this.prenomTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.prenomTB.Modified = false;
            this.prenomTB.Multiline = false;
            this.prenomTB.Name = "prenomTB";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prenomTB.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.prenomTB.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prenomTB.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.prenomTB.OnIdleState = stateProperties20;
            this.prenomTB.Padding = new System.Windows.Forms.Padding(3);
            this.prenomTB.PasswordChar = '\0';
            this.prenomTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.prenomTB.PlaceholderText = "prenom";
            this.prenomTB.ReadOnly = false;
            this.prenomTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.prenomTB.SelectedText = "";
            this.prenomTB.SelectionLength = 0;
            this.prenomTB.SelectionStart = 0;
            this.prenomTB.ShortcutsEnabled = true;
            this.prenomTB.Size = new System.Drawing.Size(200, 39);
            this.prenomTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.prenomTB.TabIndex = 6;
            this.prenomTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.prenomTB.TextMarginBottom = 0;
            this.prenomTB.TextMarginLeft = 3;
            this.prenomTB.TextMarginTop = 1;
            this.prenomTB.TextPlaceholder = "prenom";
            this.prenomTB.UseSystemPasswordChar = false;
            this.prenomTB.WordWrap = true;
            // 
            // nomTB
            // 
            this.nomTB.AcceptsReturn = false;
            this.nomTB.AcceptsTab = false;
            this.nomTB.AnimationSpeed = 200;
            this.nomTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nomTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nomTB.AutoSizeHeight = true;
            this.nomTB.BackColor = System.Drawing.Color.Transparent;
            this.nomTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nomTB.BackgroundImage")));
            this.nomTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nomTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nomTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nomTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.nomTB.BorderRadius = 1;
            this.nomTB.BorderThickness = 1;
            this.nomTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nomTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nomTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nomTB.DefaultText = "";
            this.nomTB.FillColor = System.Drawing.Color.White;
            this.nomTB.HideSelection = true;
            this.nomTB.IconLeft = null;
            this.nomTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomTB.IconPadding = 10;
            this.nomTB.IconRight = null;
            this.nomTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nomTB.Lines = new string[0];
            this.nomTB.Location = new System.Drawing.Point(21, 94);
            this.nomTB.MaxLength = 32767;
            this.nomTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.nomTB.Modified = false;
            this.nomTB.Multiline = false;
            this.nomTB.Name = "nomTB";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomTB.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nomTB.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomTB.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nomTB.OnIdleState = stateProperties24;
            this.nomTB.Padding = new System.Windows.Forms.Padding(3);
            this.nomTB.PasswordChar = '\0';
            this.nomTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nomTB.PlaceholderText = "nom";
            this.nomTB.ReadOnly = false;
            this.nomTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nomTB.SelectedText = "";
            this.nomTB.SelectionLength = 0;
            this.nomTB.SelectionStart = 0;
            this.nomTB.ShortcutsEnabled = true;
            this.nomTB.Size = new System.Drawing.Size(200, 39);
            this.nomTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.nomTB.TabIndex = 7;
            this.nomTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nomTB.TextMarginBottom = 0;
            this.nomTB.TextMarginLeft = 3;
            this.nomTB.TextMarginTop = 1;
            this.nomTB.TextPlaceholder = "nom";
            this.nomTB.UseSystemPasswordChar = false;
            this.nomTB.WordWrap = true;
            // 
            // idTB
            // 
            this.idTB.AcceptsReturn = false;
            this.idTB.AcceptsTab = false;
            this.idTB.AnimationSpeed = 200;
            this.idTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.idTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.idTB.AutoSizeHeight = true;
            this.idTB.BackColor = System.Drawing.Color.Transparent;
            this.idTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("idTB.BackgroundImage")));
            this.idTB.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.idTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.idTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.idTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.idTB.BorderRadius = 1;
            this.idTB.BorderThickness = 1;
            this.idTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.idTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.idTB.DefaultText = "";
            this.idTB.FillColor = System.Drawing.Color.White;
            this.idTB.HideSelection = true;
            this.idTB.IconLeft = null;
            this.idTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.IconPadding = 10;
            this.idTB.IconRight = null;
            this.idTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.idTB.Lines = new string[0];
            this.idTB.Location = new System.Drawing.Point(21, 49);
            this.idTB.MaxLength = 32767;
            this.idTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.idTB.Modified = false;
            this.idTB.Multiline = false;
            this.idTB.Name = "idTB";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.idTB.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.idTB.OnIdleState = stateProperties28;
            this.idTB.Padding = new System.Windows.Forms.Padding(3);
            this.idTB.PasswordChar = '\0';
            this.idTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.idTB.PlaceholderText = "stagaire id";
            this.idTB.ReadOnly = false;
            this.idTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.idTB.SelectedText = "";
            this.idTB.SelectionLength = 0;
            this.idTB.SelectionStart = 0;
            this.idTB.ShortcutsEnabled = true;
            this.idTB.Size = new System.Drawing.Size(200, 39);
            this.idTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.idTB.TabIndex = 8;
            this.idTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.idTB.TextMarginBottom = 0;
            this.idTB.TextMarginLeft = 3;
            this.idTB.TextMarginTop = 1;
            this.idTB.TextPlaceholder = "stagaire id";
            this.idTB.UseSystemPasswordChar = false;
            this.idTB.WordWrap = true;
            // 
            // dgv
            // 
            this.dgv.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgv.ColumnHeadersHeight = 40;
            this.dgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.Name = null;
            this.dgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv.HeaderForeColor = System.Drawing.Color.White;
            this.dgv.Location = new System.Drawing.Point(42, 73);
            this.dgv.Name = "dgv";
            this.dgv.ReadOnly = true;
            this.dgv.RowHeadersVisible = false;
            this.dgv.RowTemplate.Height = 40;
            this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv.Size = new System.Drawing.Size(617, 297);
            this.dgv.TabIndex = 1;
            this.dgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgv.SelectionChanged += new System.EventHandler(this.dgv_SelectionChanged);
            // 
            // mainController
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(958, 450);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "mainController";
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.mainController_Load);
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private Bunifu.UI.WinForms.BunifuTextBox searchByTB;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox ageTB;
        private Bunifu.UI.WinForms.BunifuTextBox cinTB;
        private Bunifu.UI.WinForms.BunifuTextBox addressTB;
        private Bunifu.UI.WinForms.BunifuTextBox prenomTB;
        private Bunifu.UI.WinForms.BunifuTextBox nomTB;
        private Bunifu.UI.WinForms.BunifuTextBox idTB;
        private Bunifu.UI.WinForms.BunifuLabel itemNumberLbl;
        private Guna.UI2.WinForms.Guna2CircleButton toLastBtn;
        private Guna.UI2.WinForms.Guna2CircleButton previousBtn;
        private Guna.UI2.WinForms.Guna2CircleButton nextBtn;
        private Guna.UI2.WinForms.Guna2CircleButton toZeroBtn;
        private Bunifu.UI.WinForms.BunifuImageButton resetBtn;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private Bunifu.Framework.UI.BunifuThinButton2 removeStgBtn;
        private Bunifu.Framework.UI.BunifuThinButton2 modifyStgBtn;
        private Bunifu.Framework.UI.BunifuThinButton2 addStgBtn;
        private Bunifu.UI.WinForms.BunifuImageButton exitIcon;
        private Bunifu.UI.WinForms.BunifuImageButton clearIcon;
        private Bunifu.UI.WinForms.BunifuImageButton saveChangesIcon;
    }
}

